name: Run basic tests

on:
    push:
        branches: [master, main, dev]
    pull_request:
        branches: [master, main, dev]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - run: npm install
            # - run: npm run vscode:prepublish
            - run: npm run lint
