name: Run basic tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - run: npm install
            # - run: npm run vscode:prepublish
            - run: npm run lint
